jobs:
 include:
  os:
    - osx
install:
    - HOMEBREW_NO_AUTO_UPDATE=1 brew install python3 coreutils
    - pip3 install pyzmq
before_script:
    - git clone https://github.com/bitcoin/bitcoin.git --depth 1
    - cd bitcoin
    - export SRCDIR=$(pwd)
    - echo $SRCDIR
    - cd ../
    - python3 ./download_latest_nightly.py
    - cat ./src_dir.txt
    - cat ./build_dir.txt
    - export BUILDDIR=$(tail -1 ./build_dir.txt)
    - echo $BUILDDIR
script:
    - ${BUILDDIR}/src/test_bitcoin
    - ${SRCDIR}/test/util/bitcoin-util-test.py -v
    - ${SRCDIR}/test/functional/test_runner.py --extended --coverage -x p2p_invalid_messages
after_script:
    - cd ${SRCDIR}
    - git log -1
    - cd ${BUILDDIR}
    - shasum -a 256 ./src/*
