os:
  - osx
env:
  global:
  matrix:
install:
    - HOMEBREW_NO_AUTO_UPDATE=1 brew install python3 coreutils
    - pip3 install pyzmq
before_script:
    - git clone https://github.com/bitcoin/bitcoin.git --depth 1
    - cd bitcoin
    - export SRCDIR=$(pwd)
    - cd ../
    - python3 ./download_latest_nightly.py | tee ./output
    - export BUILDDIR=$(tail -1 ./output)
script:
    - ${BUILDDIR}/src/test_bitcoin
    - ${SRCDIR}/test/util/bitcoin-util-test.py -v
    - ${SRCDIR}/test/functional/test_runner.py --extended --coverage -x feature_pruning,feature_dbcrash,wallet_backup,feature_block
after_script:
    - cd ${SRCDIR}
    - git log -1
    - cd ${BUILDDIR}
    - shasum -a 256 ./src/*
