language: bash
env: >-
   SHASUM="shasum -a 256"
   BIN="OSX"
   TEST_RUNNER_EXTRA="wallet_disable"  # Only run wallet_disable as a smoke test, see https://github.com/bitcoin/bitcoin/pull/17240#issuecomment-546022121 why the other tests are disabled
install:
    - HOMEBREW_NO_AUTO_UPDATE=1 brew install python3 coreutils
    - pip3 install pyzmq
before_script:
    - git clone https://github.com/bitcoin/bitcoin.git --depth 1 ./bitcoin-core-nightly
    - cd bitcoin-core-nightly
    - export SRCDIR=$(pwd)
    - echo $SRCDIR
    - python3 ../download_latest_nightly.py --bin="${BIN}" --srcdir="${SRCDIR}"
    - cat ./build_dir.txt
    - export BUILDDIR=$(tail -1 ./build_dir.txt)
    - echo $BUILDDIR
script:
    - ${BUILDDIR}/src/test_bitcoin
    - ${SRCDIR}/test/util/bitcoin-util-test.py -v
    - ${SRCDIR}/test/functional/test_runner.py ${TEST_RUNNER_EXTRA}
after_script:
    - cd ${SRCDIR}
    - git log -1
    - cd ${BUILDDIR}
    - $SHASUM ./src/*

jobs:
 include:
 - os: osx
 - os: linux
   arch: arm64
   env: >-
    SHASUM=sha256sum
    BIN=ARM64
    TEST_RUNNER_EXTRA="--extended"
   install:
    - sudo apt update && sudo apt install python3-zmq -y


 - os: windows
   env: >-
    SHASUM=sha256sum
    BIN=WIN
   install:
    - choco install python --version=3.7.5
    - export PYTHON="C:\Python37\python"
    - powershell "${PYTHON} --version"
    - powershell 'C:\Python37\Scripts\pip install pyzmq'
    - export PYTHONIOENCODING="UTF-8"
    - export PYTHONUTF8=1
   before_script:
    - git clone https://github.com/bitcoin/bitcoin.git --depth 1 ./bitcoin-core-nightly
    - cd bitcoin-core-nightly
    - export SRCDIR=$(pwd)
    - echo $SRCDIR
    - powershell "${PYTHON} ../download_latest_nightly.py --bin=${BIN} --srcdir=${SRCDIR}"
    - cat ./build_dir.txt
    - export BUILDDIR=$(tail -1 ./build_dir.txt)
    - echo $BUILDDIR
   script:
    - ${BUILDDIR}/src/test_bitcoin.exe
    - cd ${SRCDIR}
    - powershell "${PYTHON} ./test/util/bitcoin-util-test.py -v"
    - powershell "${PYTHON} ./test/functional/test_runner.py wallet_disable wallet_multiwallet"
