os:
  - osx
env:
  global:
    - PYTHON_DEBUG=1
  matrix:
install:
    - HOMEBREW_NO_AUTO_UPDATE=1 brew install python3 coreutils gnu-sed
    - pip3 install pyzmq
before_script:
    - git clone https://github.com/bitcoin/bitcoin.git --depth 1
    - cd bitcoin && export SRCDIR=`pwd` && cd ../
    - export BUILD_ID=`curl 'https://bitcoin.jonasschnelli.ch/build/nightly/latest'|grep embed-responsive-item|gsed -e 's/^.*builds\(\/[0-9]\+\/\).*$/\1/g'` && echo ${BUILD_ID}
    - export TAR_GITIAN_NAME=`curl "https://bitcoin.jonasschnelli.ch/builds${BUILD_ID}"|grep "\-osx64.tar.gz"|gsed -e 's/^.*\(bitcoin-0.[0-9]\+.99-osx64\.tar\.gz\).*/\1/g'` && echo ${TAR_GITIAN_NAME}
    - wget --no-verbose "https://bitcoin.jonasschnelli.ch/builds${BUILD_ID}${TAR_GITIAN_NAME}"
    - tar -xzvf ./${TAR_GITIAN_NAME}
    - cd ./bitcoin-0.*.99/bin/ && export BUILDDIR=`pwd` && mkdir src && mv ./*bitcoin* ./src/
    - cd ${SRCDIR} && cp ../config.ini ./test/
    - python -c "import os;f=open('./test/config.ini');c=f.read();c=c.replace('__BUILDDIR__', os.getenv('BUILDDIR'));c=c.replace('__SRCDIR__', os.getenv('SRCDIR'));f=open('./test/config.ini','w');f.write(c);"
script:
    - ${BUILDDIR}/src/test_bitcoin
    - ${SRCDIR}/test/util/bitcoin-util-test.py -v
    - ${SRCDIR}/test/functional/test_runner.py --extended --coverage -x feature_pruning,feature_dbcrash,wallet_backup,feature_block
after_script:
    - cd ${SRCDIR} && git log -1
    - cd ${BUILDDIR} && shasum -a 256 ./src/*
