language: bash
env: >-
   SHASUM="shasum -a 256"
install:
    - HOMEBREW_NO_AUTO_UPDATE=1 brew install python3 coreutils
    - pip3 install pyzmq
before_script:
    - git clone https://github.com/bitcoin/bitcoin.git --depth 1
    - cd bitcoin
    - export SRCDIR=$(pwd)
    - echo $SRCDIR
    - cd ../
    - python3 ./download_latest_nightly.py
    - cat ./src_dir.txt
    - cat ./build_dir.txt
    - export BUILDDIR=$(tail -1 ./build_dir.txt)
    - echo $BUILDDIR
script:
    - ${BUILDDIR}/src/test_bitcoin
    - ${SRCDIR}/test/util/bitcoin-util-test.py -v
    - ${SRCDIR}/test/functional/test_runner.py --extended --coverage -x p2p_invalid_messages,wallet_import_rescan,mining_getblocktemplate_longpoll,feature_dbcrash,feature_assumevalid
after_script:
    - cd ${SRCDIR}
    - git log -1
    - cd ${BUILDDIR}
    - $SHASUM ./src/*

jobs:
 include:
 - os: osx


 - os: windows
   env: >-
    SHASUM=sha256sum
   install:
    - choco install python --version=3.7.5
    - export PYTHON="C:\Python37\python"
    - powershell "${PYTHON} --version"
    - powershell 'C:\Python37\Scripts\pip install pyzmq'
    - export PYTHONIOENCODING="UTF-8"
    - export PYTHONUTF8=1
   before_script:
    - git clone https://github.com/bitcoin/bitcoin.git --depth 1
    - cd bitcoin
    - export SRCDIR=$(pwd)
    - echo $SRCDIR
    - cd ../
    - powershell "${PYTHON} ./download_latest_nightly.py"
    - cat ./src_dir.txt
    - cat ./build_dir.txt
    - export BUILDDIR=$(tail -1 ./build_dir.txt)
    - echo $BUILDDIR
   script:
    - ${BUILDDIR}/src/test_bitcoin.exe
    - powershell "${PYTHON} bitcoin/test/util/bitcoin-util-test.py -v"
    - powershell "${PYTHON} bitcoin/test/functional/test_runner.py wallet_disable wallet_multiwallet"
